**Importamos las librerias**

In [26]:
import re
from collections import Counter
import pandas as pd
import tools as tools
import numpy as np


**Leer el ervchivo**

In [31]:
import pandas as pd

# Cargar el CSV en un DataFrame
df = pd.read_csv('summaries.csv', encoding='utf-8')

# Extraer los títulos y resúmenes en listas
titulos = df['titulo'].tolist()
resumenes = df['resumen'].tolist()

**Imprimirmos los archivos para ver que funcione**

In [34]:
for i in range(1):
    print(titulos[i])
    print(resumenes[i])



Introduction to Epilepsy
Epilepsy is a neurological disorder characterized by recurrent seizures. These seizures are temporary episodes of abnormal electrical activity in the brain that can affect behavior, movements, sensations, and consciousness. Epilepsy is a neurological disorder characterized by recurrent seizures. These seizures are temporary episodes of abnormal electrical activity in the brain that can affect behavior, movements, sensations, and consciousness. Epilepsy is a neurological disorder characterized by recurrent seizures. These seizures are temporary episodes of abnormal electrical activity in the brain that can affect behavior, movements, sensations, and consciousness. Epilepsy is a neurological disorder characterized by recurrent seizures. These seizures are temporary episodes of abnormal electrical activity in the brain that can affect behavior, movements, sensations, and consciousness. Epilepsy is a neurological disorder characterized by recurrent seizures. These 

**Aplicar un filto**

In [3]:
import re

# Definir los documentos individualmente
d1 = "Shipment of gold damaged in a fire."
d2 = "Delivery of silver arrived in a silver truck."
d3 = "Shipment of gold arrived in a truck."

# Función para tokenizar
def tokenize(text):
    text = text.lower()  # Convertir a minúsculas
    text = re.sub(r'[^\w\s]', '', text)  # Eliminar puntuación
    return text.split()

# Leer y tokenizar cada documento por separado
documents = {"d1": d1, "d2": d2, "d3": d3}
word_dict_per_doc = {}

for key, text in documents.items():
    word_set = set(tokenize(text))  # Tokenizar cada documento por separado
    word_list = sorted(word_set)  # Ordenar palabras únicas
    word_dict_per_doc[key] = {idx + 1: word for idx, word in enumerate(word_list)}  # Crear diccionario

# Imprimir los diccionarios de palabras únicas por documento
for doc, word_dict in word_dict_per_doc.items():
    print(f"\nDiccionario de palabras únicas para {doc}:")
    for index, word in word_dict.items():
        print(f"{index}: {word}")



Diccionario de palabras únicas para d1:
1: a
2: damaged
3: fire
4: gold
5: in
6: of
7: shipment

Diccionario de palabras únicas para d2:
1: a
2: arrived
3: delivery
4: in
5: of
6: silver
7: truck

Diccionario de palabras únicas para d3:
1: a
2: arrived
3: gold
4: in
5: of
6: shipment
7: truck


In [4]:
# Crear un diccionario global con todas las palabras únicas de los tres documentos
global_word_set = set()

# Agregar todas las palabras únicas de cada documento al conjunto global
for text in documents.values():
    global_word_set.update(tokenize(text))

# Ordenar y asignar un índice a cada palabra en el diccionario global
global_word_list = sorted(global_word_set)
global_word_dict = {idx + 1: word for idx, word in enumerate(global_word_list)}

# Imprimir el diccionario global de palabras únicas
print("\nDiccionario global de palabras únicas:")
for index, word in global_word_dict.items():
    print(f"{index}: {word}")



Diccionario global de palabras únicas:
1: a
2: arrived
3: damaged
4: delivery
5: fire
6: gold
7: in
8: of
9: shipment
10: silver
11: truck


# crear la matriz de terminos frecuencia, la cual se cra a partid de los documentos de entrada

# ## 40 documentos, 20 tema 

# podriamos usar 1 archivo CSV y adentro, el titulo y el resumen asi 40 filas

# normalizar

### Lista de terminos de los 40 documentos, no se tienen que repetir en este punto,
## despues calcular la frecuencia en que aparecen esas palabras en ese documento

# guardar la descomposicion para no ejecutarla varias veces



In [5]:
# Crear la matriz A automáticamente a partir de los documentos tokenizados

# Lista global de términos únicos ordenados
global_word_list = sorted(global_word_set)

# Crear una matriz de ceros con dimensiones (número de términos únicos x número de documentos)
A = np.zeros((len(global_word_list), len(documents)), dtype=int)

# Llenar la matriz A con la frecuencia de los términos en cada documento
for j, (doc_key, text) in enumerate(documents.items()):
    word_counts = Counter(tokenize(text))  # Contar palabras en el documento
    for i, word in enumerate(global_word_list):
        A[i, j] = word_counts.get(word, 0)  # Asignar la frecuencia de la palabra

# Mostrar la matriz A generada automáticamente
print("Matriz A (término-documento):")
print(A)



Matriz A (término-documento):
[[1 1 1]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]
 [1 1 1]
 [1 0 1]
 [0 2 0]
 [0 1 1]]


In [6]:
# Definir la consulta
query_text = "gold silver truck"

# Tokenizar la consulta
query_tokens = tokenize(query_text)

# Crear la matriz de consulta q con ceros
q = np.zeros((len(global_word_list), 1), dtype=int)

# Llenar la matriz q con la frecuencia de los términos en la consulta
query_counts = Counter(query_tokens)
for i, word in enumerate(global_word_list):
    q[i, 0] = query_counts.get(word, 0)  # Asignar la frecuencia de la palabra

# Mostrar la matriz de consulta q generada automáticamente
print("Matriz q (consulta):")
print(q)



Matriz q (consulta):
[[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]]


# paso 2 decomponer la matriz A en U, S y V
# A = USV^T

In [ ]:
# Descomposición en valores singulares (SVD) de la matriz A
U, S, VT = np.linalg.svd(A, full_matrices=False)

# Obtener la matriz V a partir de la transpuesta de V^T
V = VT.T

# Convertir S en una matriz diagonal
S_matrix = np.diag(S)



# Mostrar las matrices resultantes
print("Matriz U:")
print(U)

print("\nMatriz S:")
print(S_matrix)

# Mostrar la matriz V
print("\nMatriz V:")
print(V)

print("\nMatriz V^T:")
print(VT)


Matriz U:
[[-0.42012157 -0.07479925 -0.04597244]
 [-0.29948676  0.20009226  0.40782766]
 [-0.12063481 -0.27489151 -0.4538001 ]
 [-0.157561    0.30464762 -0.2006467 ]
 [-0.12063481 -0.27489151 -0.4538001 ]
 [-0.26256057 -0.37944687  0.15467426]
 [-0.42012157 -0.07479925 -0.04597244]
 [-0.42012157 -0.07479925 -0.04597244]
 [-0.26256057 -0.37944687  0.15467426]
 [-0.315122    0.60929523 -0.40129339]
 [-0.29948676  0.20009226  0.40782766]]

Matriz S:
[[4.09887197 0.         0.        ]
 [0.         2.3615708  0.        ]
 [0.         0.         1.27366868]]

Matriz V:
[[-0.49446664 -0.64917576 -0.57799098]
 [-0.64582238  0.71944692 -0.25555741]
 [-0.58173551 -0.24691489  0.77499473]]

Matriz V^T:
[[-0.49446664 -0.64582238 -0.58173551]
 [-0.64917576  0.71944692 -0.24691489]
 [-0.57799098 -0.25555741  0.77499473]]


In [13]:
# dimencion de la matriz U
np.shape(U)

(11, 3)

# Paso 3

In [20]:
# Definir el valor de k para la aproximación de rango 2
k = 2

# Mantener solo las primeras k columnas de U
U_k = U[:, :k]

# Mantener solo las primeras k filas y columnas de S
S_k = np.diag(S[:k])

# Mantener solo las primeras k columnas de V
V_k = V[:, :k]

# Mostrar las matrices resultantes de la aproximación de rango 2
print("Matriz U_k (aproximación de rango 2):")
print(U_k)

print("\nMatriz S_k (aproximación de rango 2):")
print(S_k)

print("\nMatriz V_k (aproximación de rango 2):")
print(V_k)

print("\nMatriz V_k^T (transpuesta de V_k):")
print(V_k.T)


Matriz U_k (aproximación de rango 2):
[[-0.42012157 -0.07479925]
 [-0.29948676  0.20009226]
 [-0.12063481 -0.27489151]
 [-0.157561    0.30464762]
 [-0.12063481 -0.27489151]
 [-0.26256057 -0.37944687]
 [-0.42012157 -0.07479925]
 [-0.42012157 -0.07479925]
 [-0.26256057 -0.37944687]
 [-0.315122    0.60929523]
 [-0.29948676  0.20009226]]

Matriz S_k (aproximación de rango 2):
[[4.09887197 0.        ]
 [0.         2.3615708 ]]

Matriz V_k (aproximación de rango 2):
[[-0.49446664 -0.64917576]
 [-0.64582238  0.71944692]
 [-0.58173551 -0.24691489]]

Matriz V_k^T (transpuesta de V_k):
[[-0.49446664 -0.64582238 -0.58173551]
 [-0.64917576  0.71944692 -0.24691489]]


In [21]:
np.shape(U_k)

(11, 2)

In [ ]:
U_k

# Paso 4

In [22]:
# Paso 4: Obtener las coordenadas de los documentos en el espacio reducido de 2 dimensiones
doc_coordinates = V_k



# Paso 5

In [23]:

# Paso 5: Calcular las nuevas coordenadas de la consulta en el espacio reducido
# Se usa la ecuación q' = q^T U_k S_k^(-1)

# Invertir la matriz S_k
S_k_inv = np.linalg.inv(S_k)

# Transformar el vector de consulta
q_reduced = (q.T @ U_k) @ S_k_inv

# Mostrar los resultados
print("Coordenadas de los documentos en el espacio reducido (Paso 4):")
print(doc_coordinates)

print("\nNueva representación de la consulta en el espacio reducido (Paso 5):")
print(q_reduced)

Coordenadas de los documentos en el espacio reducido (Paso 4):
[[-0.49446664 -0.64917576]
 [-0.64582238  0.71944692]
 [-0.58173551 -0.24691489]]

Nueva representación de la consulta en el espacio reducido (Paso 5):
[[-0.21400262  0.18205705]]


# paso 6

In [25]:
# Paso 6: Ordenar los documentos según la similitud del coseno en orden descendente

from sklearn.metrics.pairwise import cosine_similarity

# Calcular la similitud del coseno entre la consulta reducida y los documentos reducidos
similarity_scores = cosine_similarity(q_reduced, doc_coordinates)  # q' vs documentos


# Crear un diccionario con los documentos y sus respectivas similitudes
doc_similarity = {doc: similarity_scores[0, i] for i, doc in enumerate(documents.keys())}

# Ordenar los documentos por similitud de coseno en orden descendente
ranked_docs = sorted(doc_similarity.items(), key=lambda x: x[1], reverse=True)

# Mostrar los resultados
print("Ranking de documentos según similitud de coseno:")
for rank, (doc, similarity) in enumerate(ranked_docs, start=1):
    print(f"{rank}. {doc} - Similitud: {similarity:.4f}")

# Mostrar el ranking final en el formato esperado
ranking_str = " > ".join([doc for doc, _ in ranked_docs])
print(f"\nOrden final de documentos: {ranking_str}")


Ranking de documentos según similitud de coseno:
1. d2 - Similitud: 0.9910
2. d3 - Similitud: 0.4480
3. d1 - Similitud: -0.0540

Orden final de documentos: d2 > d3 > d1
