**Importamos las librerias**

In [1]:
import re
from collections import Counter
import pandas as pd
import tools as tools
import numpy as np


**Leer el ervchivo**

In [2]:
import pandas as pd

# Cargar el CSV en un DataFrame
df = pd.read_csv('summaries.csv', encoding='utf-8')

# Extraer los títulos y resúmenes en listas
titulos = df['titulo'].tolist()
resumenes = df['resumen'].tolist()

In [3]:
diccionario_peliculas = dict(zip(titulos, resumenes))

**Imprimirmos los archivos para ver que funcione**

In [4]:
for i in range(5):
    print(titulos[i])


Introduction to Epilepsy
Current Treatments for Epilepsy
Causes of Epilepsy
Diagnosis of Epilepsy
Living with Epilepsy


**Aplicar un filto**

In [5]:
import re

# Función para tokenizar
def tokenize(text):
    text = text.lower()  # Convertir a minúsculas
    text = re.sub(r'[^\w\s]', '', text)  # Eliminar puntuación
    tokens = text.split()
    filtred_tokens = [word for word in tokens if len(word) >= 5]
    return filtred_tokens

**cramos nuestro diccionario de docimentos clave -> valor, titulo -> resumenes**

In [6]:
documents = {}

for i in range(len(titulos)):
    documents[titulos[i]] = resumenes[i]
# 

**Diccionario con las palabras por documento**

In [7]:
word_dict_per_doc = {}

for key, text in documents.items():
    word_set = set(tokenize(text))  # Tokenizar cada documento por separado
    word_list = sorted(word_set)  # ordenar
    
    word_dict_per_doc[key] = {idx + 1: word for idx, word in enumerate(word_list)}  # Crear diccionario

**Imprimimos nuestro diccionario por documento con palabras unicas**

In [8]:

# Imprimir los diccionarios de palabras únicas por documento
for doc, word_dict in word_dict_per_doc.items():
    print(f"\nDiccionario de palabras únicas para {doc}:")
    for index, word in word_dict.items():
        print(f"{index}: {word}")



Diccionario de palabras únicas para Introduction to Epilepsy:
1: abnormal
2: activity
3: adjustments
4: advancements
5: affect
6: affected
7: affects
8: alcohol
9: antiepileptic
10: areas
11: avoid
12: awareness
13: brain
14: brief
15: carbohydrates
16: cases
17: cause
18: caused
19: causes
20: chronic
21: classified
22: consciousness
23: consumption
24: continue
25: control
26: delivers
27: deprivation
28: detailed
29: detect
30: developmental
31: diagnosis
32: disorder
33: disorders
34: drugresistant
35: education
36: electrical
37: electroencephalogram
38: eliminate
39: epilepsy
40: exact
41: examinations
42: factors
43: falls
44: family
45: flashing
46: focal
47: fulfilling
48: generalized
49: genetic
50: hemispheres
51: history
52: identify
53: improve
54: impulses
55: include
56: increased
57: independent
58: individuals
59: infections
60: injuries
61: involuntary
62: involves
63: issues
64: jerking
65: ketogenic
66: lifestyle
67: lights
68: lives
69: living
70: management
71: m

In [9]:
# Crear un diccionario global con todas las palabras únicas de los tres documentos
global_word_set = set()

# Agregar todas las palabras únicas de cada documento al conjunto global
for text in documents.values():
    global_word_set.update(tokenize(text))

# Ordenar y asignar un índice a cada palabra en el diccionario global
global_word_list = sorted(global_word_set)
global_word_dict = {idx: word for idx, word in enumerate(global_word_list)}

# Imprimir el diccionario global de palabras únicas
print("\nDiccionario global de palabras únicas:")
for index, word in global_word_dict.items():
    print(f"{index}: {word}")

    



Diccionario global de palabras únicas:
0: ability
1: abnormal
2: about
3: accelerate
4: access
5: accidents
6: accuracy
7: accurate
8: accurately
9: across
10: active
11: activities
12: activity
13: adapted
14: additional
15: address
16: addresses
17: adherence
18: adjustments
19: adults
20: advancements
21: affect
22: affected
23: affecting
24: affects
25: alcohol
26: allowing
27: allows
28: altered
29: alternative
30: among
31: analysis
32: another
33: anticonvulsant
34: antiepileptic
35: anxiety
36: applications
37: approach
38: approaches
39: areas
40: artificial
41: associated
42: attention
43: autoimmune
44: avoid
45: avoiding
46: awareness
47: being
48: better
49: between
50: biological
51: biomedical
52: birth
53: birthrelated
54: blood
55: brain
56: brief
57: cannot
58: carbohydrates
59: cases
60: categories
61: categorized
62: cause
63: caused
64: causes
65: causing
66: challenge
67: challenges
68: challenging
69: chest
70: childhood
71: children
72: chronic
73: classificati

crear la matriz de terminos frecuencia, la cual se cra a partid de los documentos de entrada
40 documentos, 20 tema 
podriamos usar 1 archivo CSV y adentro, el titulo y el resumen asi 40 filas
normalizar
Lista de terminos de los 40 documentos, no se tienen que repetir en este punto,
despues calcular la frecuencia en que aparecen esas palabras en ese documento
guardar la descomposicion para no ejecutarla varias veces

In [10]:
print(len(global_word_list))

469


**El tamaño sera de 308**

**hacer un test con el primer documento para crear su arreglo**

In [11]:
# Crear la matriz A automáticamente a partir de los documentos tokenizados
A = np.zeros((len(global_word_list), len(documents)), dtype=int)
print(A.shape)

for i, titlulo in enumerate(titulos):
     for j, global_word in global_word_dict.items():
        if global_word in word_dict_per_doc[titulos[i]].values():
            A[j, i] = 1

print(A)

(469, 40)
[[0 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [12]:
# Crear la matriz A con ceros.
A = np.zeros((len(global_word_dict), len(titulos)), dtype=int)

# Recorremos cada documento (columna) usando el título.
for col, titulo in enumerate(titulos):
    # Tokenizamos el texto.
    tokens = tokenize(documents[titulo])    
    # Contamos la frecuencia de cada palabra en el documento.
    freq = Counter(tokens)
    
    # Recorremos cada palabra global (fila) y asignamos la frecuencia.
    for row, global_word in global_word_dict.items():
        A[row, col] = freq[global_word]  # Si la palabra no está, freq[global_word] devuelve 0

# Imprimir la forma y contenido de la matriz
print("Shape:", A.shape)
print(A)

Shape: (469, 40)
[[0 0 0 ... 0 0 0]
 [2 2 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


**Matriz del documento**

In [13]:
# Imprimir la forma y contenido de la matriz
print("Shape:", A.shape)
# ver 2 columnas y 20 filas
print(A[:10, :20])
# ver el tamaño completo de la matriz


Shape: (469, 40)
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [2 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


**Verifico que realmente me de las palabras que tengo en el dcumento o1 desde la matriz A**

In [14]:
for i, global_word in global_word_dict.items():
    if A[i, 0] != 0:  # Verifica si en el documento 1 (columna 0) la palabra está presente
        print(global_word)


abnormal
activity
adjustments
advancements
affect
affected
affects
alcohol
antiepileptic
areas
avoid
awareness
brain
brief
carbohydrates
cases
cause
caused
causes
chronic
classified
consciousness
consumption
continue
control
delivers
deprivation
detailed
detect
developmental
diagnosis
disorder
disorders
drugresistant
education
electrical
electroencephalogram
eliminate
epilepsy
exact
examinations
factors
falls
family
flashing
focal
fulfilling
generalized
genetic
hemispheres
history
identify
improve
impulses
include
increased
independent
individuals
infections
injuries
involuntary
involves
issues
jerking
ketogenic
lifestyle
lights
lives
living
management
medical
medications
moments
movements
muscle
nerve
neurological
options
originate
other
partial
patients
people
potential
proper
public
quality
recurrent
reduce
remains
removed
requires
scans
seizure
seizures
sleep
society
specific
stimulation
stress
strokes
structural
sudden
support
surgery
symptoms
tests
those
treatment
triggers
tumors

In [15]:
word_dict_per_doc[titulos[0]].values()

dict_values(['abnormal', 'activity', 'adjustments', 'advancements', 'affect', 'affected', 'affects', 'alcohol', 'antiepileptic', 'areas', 'avoid', 'awareness', 'brain', 'brief', 'carbohydrates', 'cases', 'cause', 'caused', 'causes', 'chronic', 'classified', 'consciousness', 'consumption', 'continue', 'control', 'delivers', 'deprivation', 'detailed', 'detect', 'developmental', 'diagnosis', 'disorder', 'disorders', 'drugresistant', 'education', 'electrical', 'electroencephalogram', 'eliminate', 'epilepsy', 'exact', 'examinations', 'factors', 'falls', 'family', 'flashing', 'focal', 'fulfilling', 'generalized', 'genetic', 'hemispheres', 'history', 'identify', 'improve', 'impulses', 'include', 'increased', 'independent', 'individuals', 'infections', 'injuries', 'involuntary', 'involves', 'issues', 'jerking', 'ketogenic', 'lifestyle', 'lights', 'lives', 'living', 'management', 'medical', 'medications', 'moments', 'movements', 'muscle', 'nerve', 'neurological', 'options', 'originate', 'other'

In [16]:
# Definir la consulta
query_text = "what is ontology?"

# Tokenizar la consulta
query_tokens = tokenize(query_text)

In [17]:
print(query_tokens)

['ontology']


**Consulta**

In [18]:


# Crear la matriz de consulta q con ceros
q = np.zeros((len(global_word_list), 1), dtype=int)

# Llenar la matriz q con la frecuencia de los términos en la consulta
query_counts = Counter(query_tokens)

print(query_counts) 

for i, word in enumerate(global_word_list):
    q[i, 0] = query_counts.get(word, 0)  # Asignar la frecuencia de la palabra

# Mostrar la matriz de consulta q generada automáticamente
print("Matriz q (consulta):")
print(q)

Counter({'ontology': 1})
Matriz q (consulta):
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]

**paso 2 decomponer la matriz A en U, S y V**
**A = USV^T**

In [19]:
# Descomposición en valores singulares (SVD) de la matriz A
U, S, VT = np.linalg.svd(A, full_matrices=False)
# Obtener la matriz V a partir de la transpuesta de V^T
V = VT.T
# Convertir S en una matriz diagonal
S_matrix = np.diag(S)

# Mostrar las matrices resultantes
print("Matriz U:")
print(U.shape)
print("\nMatriz S:")
print(S.shape)
# Mostrar la matriz V
print("\nMatriz V:")
print(V.shape)
print("\nMatriz V^T:")
print(VT.shape)
print("\nMatriz V^T:")
print(S_matrix.shape)


Matriz U:
(469, 40)

Matriz S:
(40,)

Matriz V:
(40, 40)

Matriz V^T:
(40, 40)

Matriz V^T:
(40, 40)


In [43]:
umbral = 0.80

# Energía total (suma de los cuadrados de los valores singulares)
energia_total = np.sum(S**2)
    
# Energía acumulada
energia_acumulada = np.cumsum(S**2)
   
# Encontrar el menor k tal que la energía acumulada supere el umbral
k = np.searchsorted(energia_acumulada / energia_total, umbral) + 1

print(k)

25


**Paso 3**

In [20]:
print(S)

[67.75304818 60.18000037 42.05589403 40.8802076  37.7403048  36.54677557
 35.22419893 33.29206665 32.04346682 31.77017441 31.27462509 30.65456562
 30.03602655 29.63829492 29.35993882 28.45898553 27.9809617  27.72645894
 27.31743454 26.92925955 26.50159553 25.6980495  25.66030516 25.06258446
 24.59644231 24.35459366 23.97750325 23.49818267 23.45460387 23.16782922
 22.39957072 22.34848888 21.70003478 21.22658921 20.99520767 20.9249891
 20.42950818 20.01203088 18.84562083 11.25312211]


**Reduccion de dimenciones**

In [51]:
# Definir el valor de k para la aproximación de rango 
k =25

# Mantener solo las primeras k columnas de U
U_k = U[:, :k]

# Mantener solo las primeras k filas y columnas de S
S_k = np.diag(S[:k])

# Mantener solo las primeras k columnas de V
V_k = V[:, :k]

VT_k = V_k.T

# Mostrar las matrices resultantes de la aproximación de rango 
print(f"Matriz U_k (aproximación de rango {k}):")
print(U_k)

print(f"\nMatriz S_k (aproximación de rango {k}):")
print(S_k)

print(f"\nMatriz V_k (aproximación de rango {k}):")
print(V_k)

print(f"\nMatriz V_k^T (transpuesta de V_k):")
print(VT_k)


Matriz U_k (aproximación de rango 25):
[[-0.01649106  0.00374826 -0.04417596 ... -0.03426805 -0.020557
   0.03309821]
 [-0.00389994 -0.01687914 -0.00665442 ... -0.00664985  0.00900337
  -0.00550483]
 [-0.00078946 -0.00403427 -0.00128423 ... -0.00462463  0.00476783
  -0.00216453]
 ...
 [-0.00087881 -0.00515461 -0.00132965 ... -0.00015759 -0.00130799
  -0.00050841]
 [-0.0277362   0.00586454 -0.00812583 ...  0.0461635  -0.08972499
  -0.04608087]
 [-0.03034395  0.00734597 -0.05711912 ... -0.02855748 -0.01185996
   0.03729225]]

Matriz S_k (aproximación de rango 25):
[[67.75304818  0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.        ]
 [ 0.         60.18000037  0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.   

**Vemos que se reducion el tamaño de las columnas = a k**

In [52]:
print(f'k = {k}')
np.shape(U_k)

k = 25


(469, 25)

# Paso 4

In [53]:
# Paso 4: Obtener las coordenadas de los documentos en el espacio reducido de 2 dimensiones
doc_coordinates = V_k
print("Coordenadas de los documentos en el espacio reducido (Paso 4):")
print('tamaño de la matriz doc_coordinates', np.shape(doc_coordinates))


Coordenadas de los documentos en el espacio reducido (Paso 4):
tamaño de la matriz doc_coordinates (40, 25)


# Paso 5

In [54]:

# Definir la consulta
query_text = "what is ontology?"
query_tokens = tokenize(query_text)
q = np.zeros((len(global_word_list), 1), dtype=int)
query_counts = Counter(query_tokens)
for i, word in enumerate(global_word_list):
    q[i, 0] = query_counts.get(word, 0)  # Asignar la frecuencia de la palabra
# Paso 5: Calcular las nuevas coordenadas de la consulta en el espacio reducido
# Se usa la ecuación q' = q^T U_k S_k^(-1)

# Invertir la matriz S_k
S_k_inv = np.linalg.inv(S_k)

# Transformar el vector de consulta
q_reduced = (q.T @ U_k) @ S_k_inv

# Mostrar los resultados
print("Coordenadas de los documentos en el espacio reducido (Paso 4):")
print(doc_coordinates)

print("\nNueva representación de la consulta en el espacio reducido (Paso 5):")
print(q_reduced)

Coordenadas de los documentos en el espacio reducido (Paso 4):
[[-4.88572100e-02 -1.10008823e-01 -5.79596186e-02  8.07799358e-03
  -1.61724283e-01  2.23072211e-02 -1.51419768e-02  1.44827111e-01
  -2.13859857e-02  1.18671985e-02  5.56500407e-02 -3.19173767e-03
  -1.65579510e-02  2.47601923e-02  2.21282321e-04  1.76461014e-02
  -1.78440416e-02 -9.42532188e-04 -6.56925407e-03 -1.20199125e-02
  -3.94428158e-02  1.29912936e-02  3.53727068e-02  9.72053949e-03
  -8.20720862e-03]
 [-5.34884428e-02 -2.42782282e-01 -5.40093552e-02  8.08111899e-02
  -2.32344885e-01 -2.38721641e-02  3.06090357e-02  3.10752273e-01
   1.60432430e-01  5.62887285e-02  7.40933501e-03 -3.22894161e-02
  -1.77765698e-01  3.35273137e-01 -2.74149354e-01  3.66484436e-01
   1.88669296e-01 -3.66775113e-02 -2.00679959e-01  1.64861948e-02
  -2.19453953e-01 -2.28617153e-02 -1.18669356e-01  1.19494169e-01
  -5.32398522e-02]
 [-5.95418465e-02 -3.10204525e-01 -5.59195885e-02 -1.63150698e-02
  -1.40613571e-01 -1.25926354e-01  7.1314

# paso 6

In [55]:
# Paso 6: Ordenar los documentos según la similitud del coseno en orden descendente

from sklearn.metrics.pairwise import cosine_similarity

# Calcular la similitud del coseno entre la consulta reducida y los documentos reducidos
similarity_scores = cosine_similarity(q_reduced, doc_coordinates)  # q' vs documentos

print(similarity_scores)


# Crear un diccionario con los documentos y sus respectivas similitudes
doc_similarity = {doc: similarity_scores[0, i] for i, doc in enumerate(documents.keys())}

# Ordenar los documentos por similitud de coseno en orden descendente
ranked_docs = sorted(doc_similarity.items(), key=lambda x: x[1], reverse=True)

resultados = []
# Mostrar los resultados
print("Ranking de documentos según similitud de coseno:")
for rank, (doc, similarity) in enumerate(ranked_docs, start=1):
    print(f"{rank}. {doc} - Similitud: {similarity:.4f}")
    resultados.append(f"{rank}. {doc} - Similitud: {similarity:.4f}")

# Mostrar el ranking final en el formato esperado
ranking_str = " > ".join([doc for doc, _ in ranked_docs])
print(f"\nOrden final de documentos: {ranking_str}")


[[ 0.03448442 -0.08301024  0.02776937  0.23445639  0.00219457 -0.09356593
   0.00101727 -0.09246554  0.01754612  0.13791971 -0.04809783 -0.10362159
   0.00927346  0.03634285 -0.03263206  0.01636679 -0.14189487 -0.02656172
   0.10279578  0.03332555 -0.08080768  0.47064741  0.02275036  0.67693475
   0.49035391 -0.1366596  -0.24822675  0.05639331 -0.19884373 -0.02437108
  -0.03022461 -0.10228138 -0.09805165 -0.08840085 -0.11058237  0.49481399
  -0.04282192 -0.05556885 -0.13588749  0.04914603]]
Ranking de documentos según similitud de coseno:
1. Clinical Applications of Ontologies - Similitud: 0.6769
2. Version Management in Ontologies - Similitud: 0.4948
3. Tools for Ontology Development - Similitud: 0.4904
4. Ontology Creation Process - Similitud: 0.4706
5. Diagnosis of Epilepsy - Similitud: 0.2345
6. Childhood Epilepsy - Similitud: 0.1379
7. Safety and Epilepsy - Similitud: 0.1028
8. Integration with EHR Systems - Similitud: 0.0564
9. Healthcare Innovation with Ontologies - Similitud: 0

In [49]:

# saber si es una lista , un diccionario
print(resultados[0])

1. Clinical Applications of Ontologies - Similitud: 0.5938


In [50]:
import langid
from googletrans import Translator

def detectar_idioma(texto):
    idioma, _ = langid.classify(texto)  # Detecta el idioma
    if idioma == "es":
        return "Español"
    elif idioma == "en":
        return "Inglés"
    else:
        return f"Otro idioma detectado: {idioma}"
    
def traducir_texto(texto, destino="en"):
    """
    Traduce un texto al idioma destino (por defecto, inglés).
    
    Args:
        texto (str): Texto a traducir.
        destino (str): Código del idioma destino (ejemplo: 'es' para español, 'en' para inglés).
    
    Returns:
        str: Texto traducido.
    """
    translator = Translator()
    traduccion = translator.translate(texto, dest=destino)
    return traduccion.text

In [40]:
def query_for_UI(query_text):
    query_tokens = tokenize(query_text)
    q = np.zeros((len(global_word_list), 1), dtype=int)
    query_counts = Counter(query_tokens)
    for i, word in enumerate(global_word_list):
        q[i, 0] = query_counts.get(word, 0) 
    S_k_inv = np.linalg.inv(S_k)
    q_reduced = (q.T @ U_k) @ S_k_inv
    similarity_scores = cosine_similarity(q_reduced, doc_coordinates)  # q' vs documentos
    print(similarity_scores)
    doc_similarity = {doc: similarity_scores[0, i] for i, doc in enumerate(documents.keys())}
    ranked_docs = sorted(doc_similarity.items(), key=lambda x: x[1], reverse=True)
    resultados = []
    for rank, (doc, similarity) in enumerate(ranked_docs, start=1):
        resultados.append(f"{rank}. {doc} - Similitud: {similarity:.4f}")
    ranking_str = " > ".join([doc for doc, _ in ranked_docs])
    print(f"\nOrden final de documentos: {ranking_str}")
    print(resultados[0])

    return resultados

In [ ]:
import tkinter as tk 
from tkinter import ttk, messagebox

class BuscadorApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Buscador de Documentos")
        self.root.geometry("600x400")
        
        # Marco para la búsqueda
        frame_busqueda = ttk.Frame(self.root, padding="10 10 10 10")
        frame_busqueda.pack(fill=tk.X)
        
        # Etiqueta y entrada de texto
        ttk.Label(frame_busqueda, text="Buscar:").pack(side=tk.LEFT, padx=(0, 5))
        self.entrada_busqueda = ttk.Entry(frame_busqueda, width=50)
        self.entrada_busqueda.pack(side=tk.LEFT, fill=tk.X, expand=True)
        
        # Botón de búsqueda
        self.boton_buscar = ttk.Button(frame_busqueda, text="Buscar", command=self.buscar)
        self.boton_buscar.pack(side=tk.LEFT, padx=(5, 0))
        
        # Lista para mostrar resultados
        frame_resultados = ttk.Frame(self.root, padding="10 10 10 10")
        frame_resultados.pack(fill=tk.BOTH, expand=True)
        
        self.lista_resultados = tk.Listbox(frame_resultados, height=15)
        self.lista_resultados.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        
        # Barra de desplazamiento
        scrollbar = ttk.Scrollbar(frame_resultados, orient=tk.VERTICAL, command=self.lista_resultados.yview)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        self.lista_resultados.config(yscrollcommand=scrollbar.set)

        # Asociar evento de doble clic para abrir el archivo
        self.lista_resultados.bind("<Double-Button-1>", self.abrir_archivo)

        
        
    def buscar(self):
        print("boton buscar")

        consulta = self.entrada_busqueda.get().strip()

        print(consulta)

        if not consulta:
            messagebox.showwarning("Entrada Vacía", "Por favor, ingresa un término de búsqueda.")
            return
        

        if detectar_idioma(consulta) == "Español":
            consulta = traducir_texto(consulta, "en")
        
        print(consulta)


        resultados = query_for_UI(consulta)

        
        # Limpiar la lista actual
        self.lista_resultados.delete(0, tk.END)
        
        if resultados:
           for i in range(len(resultados)):
               self.lista_resultados.insert(tk.END,resultados[i])
        else:
            self.lista_resultados.insert(tk.END, "No se encontraron resultados.")
        
    def abrir_archivo(self, event=None):
        seleccion = self.lista_resultados.curselection()  # Obtiene la selección actual
        print(seleccion)
        if seleccion:
            pelicula = self.lista_resultados.get(seleccion)  # Obtiene el nombre de la película seleccionada
            print(pelicula)
            resumen = diccionario_peliculas.get(pelicula, "Resumen no disponible.")  # Obtiene el resumen
            print(resumen)
            messagebox.showinfo(pelicula, resumen)  #
            

  



In [52]:

def main():
    root = tk.Tk()
    app = BuscadorApp(root)
    root.mainloop()


if __name__ == "__main__":
    main()


boton buscar

boton buscar
asdf
asdf
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Orden final de documentos: Introduction to Epilepsy > Current Treatments for Epilepsy > Causes of Epilepsy > Diagnosis of Epilepsy > Living with Epilepsy > Types of Epilepsy > Seizure Triggers > Stigma and Epilepsy > Recent Research in Epilepsy > Childhood Epilepsy > Psychological Support > Treatment Adherence > Refractory Epilepsy > Seizure Classification > Socioeconomic Impact > Epilepsy and Depression > Genetics of Epilepsy > Nocturnal Seizures > Safety and Epilepsy > Effects of Stigma > Fundamentals of Medical Ontologies > Ontology Creation Process > Interoperability in Health Systems > Clinical Applications of Ontologies > Tools for Ontology Development > Standard Medical Ontologies > Shared Semantics in Health > Integration with EHR Systems > Semantic Searching in Medicine > Semantic Interoperability > Collaboration in

Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\Users\eliut\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
TypeError: BuscadorApp.abrir_archivo() takes 1 positional argument but 2 were given


boton buscar
como estas
como estas
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Orden final de documentos: Introduction to Epilepsy > Current Treatments for Epilepsy > Causes of Epilepsy > Diagnosis of Epilepsy > Living with Epilepsy > Types of Epilepsy > Seizure Triggers > Stigma and Epilepsy > Recent Research in Epilepsy > Childhood Epilepsy > Psychological Support > Treatment Adherence > Refractory Epilepsy > Seizure Classification > Socioeconomic Impact > Epilepsy and Depression > Genetics of Epilepsy > Nocturnal Seizures > Safety and Epilepsy > Effects of Stigma > Fundamentals of Medical Ontologies > Ontology Creation Process > Interoperability in Health Systems > Clinical Applications of Ontologies > Tools for Ontology Development > Standard Medical Ontologies > Shared Semantics in Health > Integration with EHR Systems > Semantic Searching in Medicine > Semantic Interoperability > Collaboration in O